HugoRCD/shelve

apps/app/pages/app/project/[projectId]/index.vue, apps/app/pages/app/project/[projectId]/index/settings.vue, apps/app/server/app/projectService.ts
=> refactor: improve projectService.ts and fix small bug relate to teams

apps/app/components/project/CreateVariables.vue, apps/app/components/project/VariableItem.vue, apps/app/pages/app/project/[projectId]/index/variables.vue, apps/app/server/api/variable/[id]/[env].delete.ts, apps/app/server/api/variable/index.delete.ts, apps/app/server/app/variableService.ts
=> feat: add multi delete variables

.github/workflows/build.yml, .github/workflows/semantic-pull-request.yml, README.md, package.json, packages/cli/CHANGELOG.md, packages/cli/README.md, packages/cli/package.json
Introduced a new GitHub workflow to check if packages can be built on pull requests. Also, updated the name of the existing workflow for validating PR titles. Made changes in package.json files to remove 'automd' from build scripts and adjusted other related scripts accordingly. Added a license badge to the CLI README file and updated the auto-update date in both main and CLI README files.
=> feat: Add GitHub workflows and update build scripts

apps/app/app/components/token/Create.vue, apps/app/app/components/token/Toggle.vue, apps/app/app/pages/app/tokens.vue, apps/app/app/utils/navigation.ts, apps/app/server/api/protected.ts, apps/app/server/api/tokens/[id].delete.ts, apps/app/server/api/tokens/[token].get.ts, apps/app/server/api/tokens/index.get.ts, apps/app/server/api/tokens/index.post.ts, apps/app/server/app/tokenService.ts, apps/app/server/app/userService.ts, apps/app/server/database/schema.prisma, apps/app/server/middleware/1.serverAuth.ts, packages/shelve-types/eslint.config.js, packages/shelve-types/package.json, packages/shelve-types/src/CliToken.ts, packages/shelve-types/src/index.ts, packages/shelve-utils/package.json
=> feat: Add new tokens creation view

apps/app/server/app/tokenService.ts, packages/cli/package.json, packages/cli/src/commands/login.ts, packages/cli/src/commands/token.ts
=> fix: User cannot use CLI with new token system encryption

apps/app/app/components/DropdownMenu.vue, apps/app/app/components/landing/Hero.vue, apps/app/app/components/layout/Navbar.vue
=> enhancement: Add a simplier way of accessing the login page on mobile

apps/app/nuxt.config.ts, packages/cli/package.json, packages/cli/src/commands/pull.ts, packages/cli/src/commands/push.ts, packages/cli/src/utils/env.ts, packages/types/src/Cli.ts
=> feat: Add confirm changes feature to the CLI

apps/app/app/components/team/Create.vue
=> feat: Add autofocus on team create input

apps/app/app/app.vue, apps/app/app/components/ConfirmModal.vue, apps/app/app/pages/app/admin/users.vue
=> feat: Add confirm modal on user delete

apps/app/app/components/team/Members.vue, apps/app/prisma/schema.prisma, apps/app/server/api/user/teammate/index.get.ts, apps/app/server/app/teammateService.ts, apps/app/server/app/teamsService.ts
=> feat: Suggest teammates on team creation

apps/app/app/components/team/Create.vue, apps/app/server/api/teams/index.post.ts
=> fix: It's possible to create infinite empty team

apps/app/server/app/projectService.ts, apps/app/server/app/teamsService.ts
=> fix: Projects cache issue on team assign

apps/app/server/api/teams/[teamId]/index.delete.ts, apps/app/server/app/teamsService.ts
=> fix: Admin cannot delete non owner team

apps/app/app/pages/app.vue
=> feat: Detect if user is online or not

apps/lp/app/components/layout/Footer.vue
This pull request includes updates to the `Footer.vue` component in the `apps/lp/app/components/layout` directory. The most significant changes involve the removal of a status link and the addition of a status badge.
Updates to `Footer.vue`:
* Removed the 'Status' link from the navigation menu.
* Added a status badge iframe with a dark theme to display the current status.
resolve #297
=> enhancement: Update status view in the lp footer

apps/shelve/app/components/project/MainSection.vue, apps/shelve/app/composables/useVariables.ts, apps/shelve/app/pages/project/[projectId]/index.vue, apps/shelve/app/pages/projects.vue
This pull request includes several changes to the `apps/shelve` application, focusing on enhancing user experience and improving code quality. The most important changes include adding autofocus to a form input, ensuring type safety in a composable function, and updating variable names for clarity.
User experience improvements:
* [`apps/shelve/app/components/project/MainSection.vue`](diffhunk://#diff-fc7f0fd54126a5807ff9a1fe11dc123f9b7b14d558c7c9cf6964c9edc29e8b42L184-R184): Added `autofocus` to the `FormGroup` input field to enhance user experience when confirming project deletion.
Code quality improvements:
* [`apps/shelve/app/composables/useVariables.ts`](diffhunk://#diff-7a55052bccda5ee1063986d284ad08415c58615b1d66feffff2875db39adb6a6L48-R49): Added non-null assertion operator to …
=> fix: Error on project delete

apps/shelve/app/components/variable/Prefix.vue, apps/shelve/app/pages/projects/[projectId]/index/variables.vue, apps/shelve/server/api/projects/index.post.ts, packages/cli/package.json, packages/cli/src/utils/project.ts, packages/types/src/Project.ts
=> feat: Add sorting and search functionality to variables view

.github/workflows/build-app-image.yml, .github/workflows/build-lp-image.yml, apps/base/nuxt.config.ts, apps/shelve/Dockerfile, apps/shelve/entrypoint.sh, apps/shelve/package.json
=> feat: Auto migrate with docker hosting

.github/workflows/build-app-image.yml, .github/workflows/build-lp-image.yml, apps/shelve/app/components/team/Manager.vue, apps/shelve/app/components/variable/Prefix.vue, apps/shelve/app/composables/useTeams.ts, apps/shelve/app/pages/[teamSlug]/settings.vue, apps/shelve/app/pages/onboarding.vue, apps/shelve/server/services/teams.ts
=> fix: Handle slug unique constraint in toast message

apps/shelve/app/pages/[teamSlug]/members.vue, apps/shelve/server/services/members.ts, packages/types/src/Team.ts
=> fix: Update member role error

apps/shelve/server/services/resend.ts
=> feat: Make email service optionnal

apps/shelve/server/api/admin/users/[id].delete.ts, apps/shelve/server/api/admin/users/[id].put.ts, apps/shelve/server/api/teams/[teamId]/projects/[projectId]/variables/env/[envId].get.ts, apps/shelve/server/api/user/index.put.ts, apps/shelve/server/middleware/1.serverAuth.ts, apps/shelve/server/middleware/2.teamAccess.ts, apps/shelve/server/services/environments.ts, apps/shelve/server/services/user.ts, apps/shelve/server/services/variables.ts, apps/shelve/server/utils/validateAccess.ts, packages/cli/src/services/project.ts
=> enhancement: Change every throw error with createError function in the server

apps/base/assets/css/animations.css, apps/base/assets/css/base.css, apps/shelve/app/app.vue, apps/shelve/app/pages/index.vue
=> feat: Add a global loader

apps/shelve/server/database/schema.ts, packages/types/package.json
=> fix: GitHub App not working because the types package build

apps/shelve/app/components/project/Create.vue, apps/shelve/app/components/project/RepoSelector.vue, apps/shelve/app/pages/[teamSlug]/projects/[projectId]/index/settings.vue, apps/shelve/app/pages/user/integrations/github.vue, apps/shelve/server/api/github/repos/index.get.ts, apps/shelve/server/services/github.ts, packages/cli/package.json, packages/cli/src/services/project.ts
=> feat: Suggest repository linking using github sync

apps/shelve/server/services/teams.ts, apps/shelve/server/utils/cache.ts
=> fix: Team cache fails to invalidate when team member is added

apps/shelve/app/app.vue, apps/shelve/app/components/project/MainSection.vue, apps/shelve/app/components/team/Manager.vue, apps/shelve/app/composables/useEnvironments.ts, apps/shelve/app/composables/useTeams.ts, apps/shelve/app/pages/[teamSlug]/settings.vue, apps/shelve/server/api/teams/[slug]/index.put.ts, apps/shelve/server/services/teams.ts, apps/shelve/server/utils/cache.ts
resolve #407 
resolve #409 
resolve #406
=> fix: Fix several bug across the app

.github/workflows/continuous-release.yml, apps/lp/app/components/layout/Footer.vue, apps/lp/app/components/layout/Navbar.vue, apps/lp/shelve.json, docker/app-compose.local.yml, docker/lp-compose.local.yml, package.json, packages/cli/README.md, packages/cli/package.json, packages/types/package.json, packages/utils/README.md, packages/utils/package.json, pnpm-lock.yaml
=> fix: Weird marker on li

apps/lp/app/pages/[...slug].vue, apps/lp/nuxt.config.ts, apps/lp/package.json, apps/lp/public/robots.txt, pnpm-lock.yaml
=> feat: 404 Page in the docs section

apps/base/modules/visitors/index.ts, apps/base/modules/visitors/runtime/composables/useVisitors.ts, apps/base/modules/visitors/runtime/server/api/visitors.ts, apps/lp/app/components/landing/Stats.vue, packages/types/src/Stats.ts, server/api/stats/ws.ts, server/utils/stats.ts
=> feat: Create real-time visitors module

apps/lp/app/components/landing/Faq.vue, apps/lp/app/components/landing/Features.vue, apps/lp/app/components/landing/Hero.vue, apps/lp/app/pages/index.vue, apps/lp/content.config.ts, apps/lp/content/index.yml
=> feat: Better `@nuxt/content` support

apps/shelve/app/pages/admin/index.vue, apps/shelve/server/api/admin/cache.delete.ts
=> feat: admin button to delete cache

apps/lp/app/app.vue, apps/lp/nuxt.config.ts, apps/lp/package.json, pnpm-lock.yaml
=> feat: add `llms.txt` module

apps/lp/content/docs/3.cli/5.push-pull.md, packages/cli/package.json, packages/cli/schema.json, packages/cli/src/commands/pull.ts, packages/cli/src/commands/push.ts, packages/cli/src/commands/run.ts, packages/cli/src/services/environment.ts
=> feat(cli): add default env to more commands

README.md, apps/lp/app/app.vue, apps/lp/app/components/Header.vue, apps/lp/app/components/layout/Footer.vue, apps/lp/app/components/layout/Navbar.vue, apps/lp/app/layouts/docs.vue, apps/lp/app/pages/blog/[...slug].vue, apps/lp/app/pages/docs/[...slug].vue, apps/lp/content.config.ts, apps/lp/content/docs/1.getting-started/1.index.md, apps/lp/content/docs/1.getting-started/2.quickstart.md, apps/lp/content/docs/2.core-features/projects.md, apps/lp/content/docs/2.core-features/teams.md, apps/lp/content/docs/2.core-features/variables.md, apps/lp/content/docs/3.cli/2.index.md, apps/lp/content/docs/6.contributing/1.index.md, apps/lp/content/index.yml, apps/lp/nuxt.config.ts, apps/lp/package.json, packages/cli/README.md, pnpm-lock.yaml
=> docs: improve-structure

apps/shelve/server/database/schema.ts
=> fix: foreign key on team deletion

apps/shelve/app/composables/useVariables.ts
=> fix: handle env duplicates

apps/shelve/app/components/variable/Create.vue, apps/shelve/app/components/variable/Item.vue, apps/shelve/app/components/variable/Selector.vue, apps/shelve/app/pages/[teamSlug]/projects/[projectId]/index/variables.vue
=> enhancement: Shift + click to select multiples variables

apps/lp/package.json, apps/shelve/app/components/variable/Create.vue, package.json, pnpm-lock.yaml
=> fix: handle the case where a key has multiple values

apps/base/components/Separator.vue, apps/shelve/app/components/variable/Create.vue, packages/cli/package.json, packages/cli/src/commands/run.ts
=> fix(cli): `nr` is undefined without shamefully-hoist=true

packages/cli/package.json, packages/cli/src/commands/run.ts, pnpm-lock.yaml
=> fix: improve detection and termination of orphan child processes

apps/base/components/CustomButton.vue, apps/shelve/app/components/project/Create.vue, apps/shelve/app/components/team/AddMember.vue, apps/shelve/app/components/token/Create.vue, apps/shelve/app/layouts/app.vue, apps/shelve/app/pages/[teamSlug]/environments.vue, apps/shelve/app/pages/admin/index.vue, apps/shelve/app/pages/user/tokens.vue, pnpm-lock.yaml
=> feat: improve app design

apps/base/components/ShelveMeta.vue, apps/shelve/app/components/layout/Navbar.vue, apps/shelve/app/layouts/app.vue
=> feat: improve mobile support and responsive

apps/base/package.json, apps/lp/package.json, apps/shelve/package.json, apps/vault/package.json, pnpm-lock.yaml
=> chore: remove `nuxt-og-image` pinned dependency

apps/shelve/app/assets/css/index.css, apps/shelve/app/components/setting/ThemeToggle.vue, apps/shelve/app/composables/useTeams.ts, apps/shelve/app/layouts/auth.vue, apps/shelve/app/pages/admin/index.vue, apps/shelve/app/pages/onboarding.vue, apps/shelve/nuxt.config.ts, apps/shelve/server/api/admin/users/[id].delete.ts, apps/shelve/server/api/user/index.delete.ts, apps/shelve/server/services/github.ts
=> enhancement(app): overall post 2.0 improvements

apps/lp/app/components/Header.vue, apps/lp/app/pages/docs/[...slug].vue, apps/shelve/app/components/project/RepoSelector.vue, apps/shelve/app/composables/useGitHub.ts, apps/shelve/app/pages/admin/index.vue, apps/shelve/server/api/github/repos/index.get.ts, apps/shelve/server/api/github/secrets/index.post.ts, apps/shelve/server/services/github.ts
=> feat(app): add `useGitHub` composable

docker/app-compose.coolify.yml
This replaces some hard-coded things like Postgres password with generated password, removes fixed container names, removes unnecessary external network, etc.. Works great for me on the latest version of Coolify.
=> chore(app): improve `app-compose.coolify.yml`

apps/base/package.json, pnpm-lock.yaml
=> fix(lp): nuxt-visitors throwing error

apps/shelve/server/services/user.ts
=> fix(app): `handleOAuthUser` uses email for verification instead of email

apps/shelve/app/components/project/RepoSelector.vue, apps/shelve/app/composables/useGitHub.ts, apps/shelve/app/composables/useRepoSearch.ts, apps/shelve/app/pages/[teamSlug]/projects/create.vue, apps/shelve/server/api/github/repos/index.get.ts
=> fix(app): improve `RepoSelector` component

apps/shelve/app/components/variable/Create.vue, apps/shelve/app/composables/useVariableForm.ts, apps/shelve/app/pages/user/settings.vue
=> feat(app): save `syncWithGithub` in cookie

apps/lp/content/docs/5.self-hosting/1.vercel.md, apps/lp/content/docs/5.self-hosting/2.environment-variables.md
=> feat(lp): add vercel self-hosting docs

.gitignore, apps/shelve/app/components/DatePopover.vue, apps/shelve/app/components/variable/Item.vue, apps/shelve/app/pages/[teamSlug]/environments.vue, apps/shelve/app/pages/[teamSlug]/members.vue, apps/shelve/app/pages/admin/index.vue, apps/shelve/app/pages/user/tokens.vue
=> refactor(app): improve members table and date across the app

apps/lp/app/app.vue, apps/lp/app/components/layout/Footer.vue, apps/lp/app/composables/useFooterLinks.ts, apps/lp/app/layouts/blog.vue, apps/lp/app/layouts/docs.vue, apps/lp/app/pages/legal/[...slug].vue, apps/lp/content.config.ts, apps/lp/content/legal/privacy.md, apps/lp/content/legal/terms.md
=> feat(lp): add terms and privacy notice
